version: '3.8'
services:
  ecommerce:
    image: "safeerep/ep-cart:latest"
    ports:
      - "7777:3001"
    env_file:
      - .env
    depends_on:
      - mongodb
    networks:
      - epcart-network

  mongodb:
    image: "mongo:latest"
    ports:
      - "27017:27017"
    networks:
      - epcart-network
    environment:
      MONGO_INITDB_DATABASE: ecommerce

networks:
  epcart-network: